[tool.poetry]
name = "repl_python3_beta_x"
version = "0.1.0"
description = ""
authors = ["JOEL123X <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
bitcoin = "^1.1.42"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
